print("===============================")
print("\t AI Journey")
print("===============================")
name=input("NAME: ")
print("welcome(name) to AI Journey")
print("phase 1: python + API")
print("phase 2: machine learning")
print("phase 3: LLM Application")
print("phase 4: RAG")
print("phase 5: Agentic AI")
print("phase 6: AWS")
print("phase 7: AGI")
print("phase 8: ASI (Artificial Super Intelligence)")